
Neos:
  ContentRepository:
    Search:
      indexAllWorkspaces: true
      elasticSearch:
        indexName: typo3cr
        log:
          backendOptions:
            fileBackend:
              logFileURL: '%FLOW_PATH_DATA%Logs/ElasticSearch.log'
              createParentDirectories: true
              severityThreshold: '%LOG_DEBUG%'
              maximumLogFileSize: 10485760
              logFilesToKeep: 1
              logMessageOrigin: false
            ansiConsoleBackend:
              disableAnsi: false
      defaultConfigurationPerType:
        string:
          elasticSearchMapping:
            type: string
            include_in_all: false
        boolean:
          elasticSearchMapping:
            type: boolean
        integer:
          elasticSearchMapping:
            type: integer
        DateTime:
          elasticSearchMapping:
            type: date
            format: date_time_no_millis
            include_in_all: false
        Neos\Media\Domain\Model\Asset:
          elasticSearchMapping: ''
        array<Neos\Media\Domain\Model\Asset>:
          elasticSearchMapping: ''
        Neos\Media\Domain\Model\ImageInterface:
          elasticSearchMapping: ''
        references:
          elasticSearchMapping:
            type: string
            index: not_analyzed
        reference:
          elasticSearchMapping:
            type: string
            index: not_analyzed
